# Generated by Django 5.1.4 on 2025-04-07 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'GUEST'},
        ),
    ]
