# Generated by Django 5.1.4 on 2025-03-29 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('icons', models.ImageField(blank=True, null=True, upload_to='images')),
                ('is_available', models.BooleanField(default=True)),
                ('availability_start', models.DateTimeField(blank=True, null=True)),
                ('availability_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=25, unique=True)),
                ('room_size', models.CharField(blank=True, max_length=128, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('room_desc', models.CharField(default='This is a Best Room', max_length=128)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_rooms', models.IntegerField(blank=True, null=True)),
                ('available_rooms', models.IntegerField(blank=True, null=True)),
                ('amenities', models.ManyToManyField(blank=True, to='hotel.amenity')),
            ],
        ),
        migrations.CreateModel(
            name='Room_Category_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.room_category')),
            ],
        ),
    ]
