# Generated by Django 5.1.4 on 2025-04-07 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_room_category_relation_remove_room_category_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='room_category_relation',
        ),
        migrations.RemoveField(
            model_name='room_category',
            name='available_rooms',
        ),
    ]
