# Generated by Django 5.1.4 on 2025-03-29 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Booking', '0001_initial'),
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(default='PAYMENT INITIATED', max_length=128)),
                ('transaction_id', models.CharField(blank=True, max_length=128, null=True)),
                ('amount_paid', models.IntegerField(default=0)),
                ('currency', models.CharField(default='INR', max_length=15)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_after_booking', to='Booking.booking')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_user.customuser')),
            ],
        ),
    ]
