# Generated by Django 5.1.4 on 2025-03-29 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='discountPercentages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time_Period', models.CharField(max_length=10)),
                ('Discount_Percentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_category', models.CharField(choices=[('room_only', 'Room Only'), ('hb', 'Half Board'), ('fb', 'Full Board')], max_length=225, unique=True)),
                ('meal_price', models.DecimalField(decimal_places=2, default='room_only', max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('no_of_rooms', models.IntegerField(default=1)),
                ('no_of_days', models.IntegerField(blank=True, default=1, null=True)),
                ('room_price_per_night_offered', models.FloatField(default=0.0)),
                ('no_of_room', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
                ('room_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.room_category')),
            ],
        ),
    ]
