# Generated by Django 5.1.4 on 2025-04-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='room_price_per_night_offered',
            new_name='price_per_night',
        ),
    ]
