# Generated by Django 5.1.4 on 2025-04-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_rename_room_price_per_night_offered_booking_price_per_night'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room_price',
        ),
    ]
