# Generated by Django 5.1.4 on 2025-04-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_remove_booking_room_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='no_of_rooms',
        ),
        migrations.AlterField(
            model_name='booking',
            name='no_of_room',
            field=models.IntegerField(default=1),
        ),
    ]
