# Generated by Django 5.1.4 on 2025-04-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_remove_booking_no_of_rooms_alter_booking_no_of_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
