# Generated by Django 5.1.4 on 2025-04-05 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0006_booking_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='invoice',
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.FileField(upload_to='invoices/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Booking.booking')),
            ],
        ),
    ]
