# Generated by Django 5.1.4 on 2025-04-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0008_alter_invoice_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_type',
            name='meal_category',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
